[package]
name = "emoji-optimizer"
version = "0.1.0"
description = "An emoji Optimizer. Analyze and count specific pixels to optimize space and image dynamism."
authors = ["braniacs"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "emoji_optimizer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
base64 = "0.22.1"
image = "0.25.6"
anyhow = "1.0.98"
log = "0.4.27"
tokio = "1.45.1"
tauri-plugin-log = "2.5.0"

